### ISSUE TITLE
SCREAMING? I AM SCREAMING FOR MERGE PERMISSIONS

### ISSUE THREAD

**Issue by Wolvan** [void-to-scream-into/scream#2]
AS STATED ABOVE, I WANNA HELP OUT WITH THIS REPO SO I WANT MERGE PERMISSIONS

**Comment by invalidCards** [comment]
YOU HAVE BEEN GIVEN AN INVITATION TO THE TEAM. ACCEPT IT AND YOU TOO WILL BE ABLE TO MERGE SCREAMS.

**Comment by Wolvan** [comment]
I VERY MUCH APPRECIATE IT, @ThePsionic

**Comment by invalidCards** [comment]
NO PROBLEM TBH
